### PR TITLE
Pass style prop to component

### PR DESCRIPTION
**Pull request by ryancoughlin**
Let users pass a `style` prop down to the components to update styling as need be. This doesn't lock a given user down to exposed properties.

### CODE REVIEW

**Comment by ryancoughlin** [comment]
@geremih Thoughts on this PR?

**Comment by asbjornenge** [comment]
Oh, I need this 🎉  Do you have your fork on github @ryancoughlin ?

//cc @geremih

**Comment by geremih** [comment]
Thanks @ryancoughlin. Can you update to the PR to only have the requested change? Formatting changes are fine, but there are some non-formatting changes that would break current behaviour.

**Comment by ryancoughlin** [comment]
Yes, will tackle this later tonight. Been using it on a production product and I haven’t had any issues.

**Comment by realpratiknikam** [comment]
@ryancoughlin any plans to update PR anytime soon?

**Pull request closed without merging**
