### PR TITLE
Use 'prop-types' for React 16

### PR DESCRIPTION
**Pull request by skhameneh-strive**

### CODE REVIEW

**Comment by geremih** [comment]
@skhameneh-strive thanks for the PR! Would this require a bump in the minimum react dependency too?

**Comment by skhameneh-strive** [comment]
I'm sure it does.  You may want to specify "15.5.7", I'll leave that up to you.

**Comment by DineshRajput21** [comment]
it's not working with expo.
can anyone please help me ?

**Comment by DineshRajput21** [comment]
facing issue Cannot read property 'number' of undefined now

**Pull request closed without merging**
