### PR TITLE
Added an 'onOverlayPress' prop

### PR DESCRIPTION
**Pull request by Ajackster**
First I would like to say how amazing this component is and how much of a help it is to my project. I think it'd be very helpful to other people using this component to have an 'onOverlayPress' prop in case they want to change state or fire off their own custom actions. It works wonders in my project.

Thank you so much!

### CODE REVIEW

**Comment by geremih** [comment]
Hey @Ajackster, thanks for the appreciation and the pull request!

I would have expected for the `backdrop` prop to be used  for custom logic on the overlay. Is there any reason you chose against it?

**Comment by Ajackster** [comment]
From my understanding, the `backdrop` prop is used to plug in your own custom component. I felt like it was extra steps for the job I needed to be done which was use the default overlay component and add in a quick function that would add functionality to the `reset()` function.

**Comment by geremih** [comment]
Alright, sounds like it would be useful for others too. Do mind updating the README to reflect your change and then I'll merge it?

**Comment by geremih** [comment]
Thanks a lot!

**Pull request merged**
